version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=key
      - YANDEX_KEY=yakey
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

