version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./tourist_guide/result:/app/tourist_guide/result
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
